# Goal
# patrol_poses: an Array of poses. 
    # If it only has one pose, the robot will go investigate that pose and stay there.
    # If it has more than one pose, the robot will go check sequentially to each pose on the list, repeating the process after the last pose.
# robotIndex: tells which robot should execute the action.

int32 robotIndex
geometry_msgs/PoseArray patrol_poses

---
# Result
# robotIndex: tells which robot executed the action.
# status: status of the robot (what it is doing at the moment).
int32 robotIndex
string status 

---
# Feedback
# this action doesn't provide any feedback. 
